<?php

use Phalcon\Tag;

// Set Document Type
$this->tag->setDoctype(Tag::HTML5);
echo $this->tag->getDoctype(); ?>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
<head>
    <?php echo $this->tag->getTitle(); ?>
    <?php echo headerMeta(); ?>
    <?php echo showFavicon(); ?>
    <?php echo $this->tag->stylesheetLink( 'https://fonts.googleapis.com/css?family=Montserrat|Quicksand:400,500,600,700&display=swap' ); ?>
    <?php echo $this->tag->stylesheetLink( 'https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css' ); ?>
    <?php echo $this->tag->stylesheetLink( 'css/base.css' ); ?>
</head>
<body>
<div class="site-page__wrapper">

    <!-- BEGIN HEADER -->
    <div class="site-page__header">
        <div class="site-page__header-inner">
            
            <div class="container is-widescreen">
                <nav class="navbar is-primary has-shadow is-spaced">
                    <div class="navbar-brand">
                        <a class="navbar-item main-logo" href="<?php echo BASE_URL; ?>">
                            <h3 class="title"><span class="fas fa-plus-square"></span> Coviduvidapdap</h3>
                        </a>
                        <div class="navbar-burger burger" data-target="mainNavBar">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div id="mainNavBar" class="navbar-menu">
                        <?php echo displayMenu(); ?>
                    </div>
                </nav><!-- .navbar -->
            </div>

        </div><!-- .site-page__header-inner -->
    </div><!-- .site-page__header -->
    <!-- END HEADER -->

    <!-- BEGIN MAIN -->
    <main class="site-page__content">
        <div class="site-page__content-inner">

            <div class="site-page__confirmed-cases container">
                <div class="columns">
                    <div class="column">
                        <p>site content ongoing.</p>
                    </div>
                </div>
            </div>

        </div><!-- .site-page__content-inner -->
    </main><!-- .site-page__content -->
    <!-- END MAIN -->

    <?php echo footerContents(); ?>

</div><!-- .site-page__wrapper -->

<?php echo $this->tag->javascriptInclude( 'https://use.fontawesome.com/releases/v5.3.1/js/all.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'https://cdn.jsdelivr.net/npm/sticky-table-headers@0.1.24/js/jquery.stickytableheaders.min.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'js/base.js' ); ?>
</body>
</html>