<?php

use Phalcon\Tag;

// Check user country code.
$country_code = ! empty( $_SERVER["HTTP_CF_IPCOUNTRY"] ) ? strtolower( $_SERVER["HTTP_CF_IPCOUNTRY"] ) : 'unknown';

// Set Document Type
$this->tag->setDoctype(Tag::HTML5);
echo $this->tag->getDoctype(); ?>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
<head>
    <?php echo $this->tag->getTitle(); ?>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <?php echo $this->tag->stylesheetLink( 'https://fonts.googleapis.com/css?family=Montserrat|Quicksand:400,500,600,700&display=swap' ); ?>
    <?php echo $this->tag->stylesheetLink( 'https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css' ); ?>
    <?php echo $this->tag->stylesheetLink( 'css/base.css' ); ?>
</head>
<body>
<div class="site-page__wrapper">

    <!-- BEGIN HEADER -->
    <div class="site-page__header">
        <div class="site-page__header-inner">
            
            <div class="container is-widescreen">
                <nav class="navbar is-primary has-shadow is-spaced">
                    <div class="navbar-brand">
                        <a class="navbar-item main-logo" href="<?php echo BASE_URL; ?>">
                            <h3 class="title">Coviduvidapdap</h3>
                        </a>
                        <div class="navbar-burger burger" data-target="mainNavBar">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div id="mainNavBar" class="navbar-menu">
                        <div class="navbar-start">
                        </div>

                        <?php echo displayMenu(); ?>
                    </div>
                </nav><!-- .navbar -->
            </div>

        </div><!-- .site-page__header-inner -->
    </div><!-- .site-page__header -->
    <!-- END HEADER -->

    <!-- BEGIN MAIN -->
    <main class="site-page__content">
        <div class="site-page__content-inner">
            
            <div class="site-page__welcome-msg container is-widescreen">
                <div class="columns">
                    <div class="column is-full">
                        <div class="tags are-medium">
                            <span class="tag">Novel Coronavirus COVID-19 <br /> Pandemic Total Cases</span>
                        </div>
                    </div>
                </div>
            </div>

            <?php 
                // Initiate get counts.
                $ch = curl_init();
                curl_setopt( $ch, CURLOPT_SSL_VERIFYPEER, false );
                curl_setopt( $ch, CURLOPT_RETURNTRANSFER, true );
                curl_setopt( $ch, CURLOPT_URL, 'https://corona.lmao.ninja/all' );
                $result = curl_exec( $ch );
                curl_close( $ch );

                $current_counts_obj = json_decode( $result );
            ?>

            <div class="site-page__confirmed-cases container">
                <div class="columns is-flex">
                    <div class="column is-1"></div>
                    <div class="column sub-cases">
                        <h3 class="subtitle has-text-success">Recovered</h3>
                        <span class="subcounter has-text-grey"><?php echo number_format( $current_counts_obj->recovered ); ?></span>
                    </div>

                    <div class="column main-cases">
                        <h1 class="title">Confirmed Cases</h1>
                        <span class="maincounter has-text-dark"><?php echo number_format( $current_counts_obj->cases ); ?></span>
                    </div>

                    <div class="column sub-cases">
                        <h3 class="subtitle has-text-danger">Deaths</h3>
                        <span class="subcounter has-text-grey"><?php echo number_format( $current_counts_obj->deaths ); ?></span>
                    </div>
                    <div class="column is-1"></div>
                </div>
            </div>

        </div><!-- .site-page__content-inner -->
    </main><!-- .site-page__content -->
    <!-- END MAIN -->

    <!-- BEGIN FOOTER -->
    <footer class="site-page__footer">
        <div class="site-page__footer-inner">
            
            <div class="site-page__copyright container is-widescreen">
                <div class="columns">
                    <div class="column">
                        <p class="credits"><?php printf( 'made with <span class="fas fa-heart"></span> by <a href="https://github.com/KSym04/coviduvidapdap" target="_blank" rel="nofollow noopener">%s</a> <br /> <sub>Keep Safe Everyone!</sub>', 'Ken' ); ?></p>
                    </div>
                </div>
            </div>

        </div><!-- .site-page__footer-inner -->
    </footer><!-- .site-page__footer -->
    <!-- END FOOTER -->

</div><!-- .site-page__wrapper -->

<?php echo $this->tag->javascriptInclude( 'https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'https://use.fontawesome.com/releases/v5.3.1/js/all.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'js/base.js' ); ?>
</body>
</html>