<?php

use Phalcon\Tag;

// Set Document Type
$this->tag->setDoctype(Tag::HTML5);
echo $this->tag->getDoctype(); ?>
<html itemscope="" itemtype="http://schema.org/WebPage" lang="en">
<head>
    <?php echo $this->tag->getTitle(); ?>
    <?php echo headerMeta(); ?>
    <?php echo showFavicon(); ?>
    <?php echo $this->tag->stylesheetLink( 'https://fonts.googleapis.com/css?family=Montserrat|Quicksand:400,500,600,700&display=swap' ); ?>
    <?php echo $this->tag->stylesheetLink( 'https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.12.1/css/all.min.css' ); ?>
    <?php echo $this->tag->stylesheetLink( 'https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css' ); ?>
    <?php echo $this->tag->stylesheetLink( 'css/base.css?v=' . $GLOBALS['siteversion'] ); ?>
</head>
<body>
<div class="site-page__wrapper">

    <!-- BEGIN HEADER -->
    <div class="site-page__header">
        <div class="site-page__header-inner">
            
            <div class="container is-widescreen">
                <nav class="navbar is-primary has-shadow is-spaced">
                    <div class="navbar-brand">
                        <a class="navbar-item main-logo" href="<?php echo BASE_URL; ?>">
                            <h3 class="title"><span class="fas fa-plus-square"></span> Coviduvidapdap</h3>
                        </a>
                        <div class="navbar-burger burger" data-target="mainNavBar">
                            <span></span>
                            <span></span>
                            <span></span>
                        </div>
                    </div>

                    <div id="mainNavBar" class="navbar-menu">
                        <?php echo displayMenu(); ?>
                    </div>
                </nav><!-- .navbar -->
            </div>

        </div><!-- .site-page__header-inner -->
    </div><!-- .site-page__header -->
    <!-- END HEADER -->

    <!-- BEGIN MAIN -->
    <main class="site-page__content">
        <div class="site-page__content-inner">

            <div class="site-page__default container">
                <div class="columns">
                    <div class="column is-1"></div>
                    <div class="column">
                        <h1>Covid-19 Myth Busters</h1>

                        <h3 class="title is-4">1. COVID-19 virus can be transmitted in areas with hot and humid climates</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            From the evidence so far, the COVID-19 virus can be transmitted in ALL AREAS, including areas with hot and humid weather. Regardless of climate, adopt protective measures if you live in, or travel to an area reporting COVID-19. The best way to protect yourself against COVID-19 is by frequently cleaning your hands. By doing this you eliminate viruses that may be on your hands and avoid infection that could occur by then touching your eyes, mouth, and nose.
                        </p>

                    <hr />

                        <h3 class="title is-4">2. Cold weather and snow CANNOT kill the new coronavirus</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            There is no reason to believe that cold weather can kill the new coronavirus or other diseases. The normal human body temperature remains around 36.5°C to 37°C, regardless of the external temperature or weather. The most effective way to protect yourself against the new coronavirus is by frequently cleaning your hands with alcohol-based hand rub or washing them with soap and water.
                        </p>

                    <hr />

                        <h3 class="title is-4">3. Taking a hot bath does not prevent the new coronavirus disease</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            Taking a hot bath will not prevent you from catching COVID-19. Your normal body temperature remains around 36.5°C to 37°C, regardless of the temperature of your bath or shower. Actually, taking a hot bath with extremely hot water can be harmful, as it can burn you. The best way to protect yourself against COVID-19 is by frequently cleaning your hands. By doing this you eliminate viruses that may be on your hands and avoid infection that could occur by then touching your eyes, mouth, and nose.
                        </p>

                    <hr />

                        <h3 class="title is-4">4. The new coronavirus CANNOT be transmitted through mosquito bites</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            To date there has been no information nor evidence to suggest that the new coronavirus could be transmitted by mosquitoes. The new coronavirus is a respiratory virus which spreads primarily through droplets generated when an infected person coughs or sneezes, or through droplets of saliva or discharge from the nose. To protect yourself, clean your hands frequently with an alcohol-based hand rub or wash them with soap and water. Also, avoid close contact with anyone who is coughing and sneezing.
                        </p>

                    <hr />

                        <h3 class="title is-4">5. Are hand dryers effective in killing the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            No. Hand dryers are not effective in killing the 2019-nCoV. To protect yourself against the new coronavirus, you should frequently clean your hands with an alcohol-based hand rub or wash them with soap and water. Once your hands are cleaned, you should dry them thoroughly by using paper towels or a warm air dryer.
                        </p>

                    <hr />

                        <h3 class="title is-4">6. Are hand dryers effective in killing the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            UV lamps should not be used to sterilize hands or other areas of skin as UV radiation can cause skin irritation.
                        </p>

                    <hr />

                        <h3 class="title is-4">7. How effective are thermal scanners in detecting people infected with the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            Thermal scanners are effective in detecting people who have developed a fever (i.e. have a higher than normal body temperature) because of infection with the new coronavirus.<br /><br />

                            However, they cannot detect people who are infected but are not yet sick with fever. This is because it takes between 2 and 10 days before people who are infected become sick and develop a fever.
                        </p>

                    <hr />

                        <h3 class="title is-4">8. Can spraying alcohol or chlorine all over your body kill the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            No. Spraying alcohol or chlorine all over your body will not kill viruses that have already entered your body. Spraying such substances can be harmful to clothes or mucous membranes (i.e. eyes, mouth). Be aware that both alcohol and chlorine can be useful to disinfect surfaces, but they need to be used under appropriate recommendations.
                        </p>

                    <hr />

                        <h3 class="title is-4">9. Do vaccines against pneumonia protect you against the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i>
                            No. Vaccines against pneumonia, such as pneumococcal vaccine and Haemophilus influenza type B (Hib) vaccine, do not provide protection against the new coronavirus.<br /><br />

                            The virus is so new and different that it needs its own vaccine. Researchers are trying to develop a vaccine against 2019-nCoV, and WHO is supporting their efforts.<br /><br />

                            Although these vaccines are not effective against 2019-nCoV, vaccination against respiratory illnesses is highly recommended to protect your health.
                        </p>

                    <hr />

                        <h3 class="title is-4">10. Can regularly rinsing your nose with saline help prevent infection with the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i>
                            No. There is no evidence that regularly rinsing the nose with saline has protected people from infection with the new coronavirus.<br /><br />

                            There is some limited evidence that regularly rinsing nose with saline can help people recover more quickly from the common cold. However, regularly rinsing the nose has not been shown to prevent respiratory infections.
                        </p>

                    <hr />

                        <h3 class="title is-4">11. Can eating garlic help prevent infection with the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            Garlic is a healthy food that may have some antimicrobial properties. However, there is no evidence from the current outbreak that eating garlic has protected people from the new coronavirus.
                        </p>

                    <hr />

                        <h3 class="title is-4">12. Does the new coronavirus affect older people, or are younger people also susceptible?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i>
                            People of all ages can be infected by the new coronavirus (2019-nCoV). Older people, and people with pre-existing medical conditions (such as asthma, diabetes, heart disease) appear to be more vulnerable to becoming severely ill with the virus.<br /><br />

                            WHO advises people of all ages to take steps to protect themselves from the virus, for example by following good hand hygiene and good respiratory hygiene.
                        </p>

                    <hr />

                        <h3 class="title is-4">13. Are antibiotics effective in preventing and treating the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i>
                            No, antibiotics do not work against viruses, only bacteria.<br /><br />

                            The new coronavirus (2019-nCoV) is a virus and, therefore, antibiotics should not be used as a means of prevention or treatment.<br /><br />

                            However, if you are hospitalized for the 2019-nCoV, you may receive antibiotics because bacterial co-infection is possible.
                        </p>

                    <hr />

                        <h3 class="title is-4">14. Are there any specific medicines to prevent or treat the new coronavirus?</h3>

                        <p>
                            <i class="fas fa-check-circle has-text-success"></i> 
                            To date, there is no specific medicine recommended to prevent or treat the new coronavirus (2019-nCoV).<br /><br />
                            
                            However, those infected with the virus should receive appropriate care to relieve and treat symptoms, and those with severe illness should receive optimized supportive care. Some specific treatments are under investigation, and will be tested through clinical trials. WHO is helping to accelerate research and development efforts with a range or partners.
                        </p>

                    <hr />

                        <em><strong>Source: <a href="https://www.who.int/" rel="nofollow noopener">World Health Organization (WHO)</a></strong></em>

                    </div>
                    <div class="column is-1"></div>
                </div>
            </div>

        </div><!-- .site-page__content-inner -->
    </main><!-- .site-page__content -->
    <!-- END MAIN -->

    <?php echo footerContents(); ?>

</div><!-- .site-page__wrapper -->

<?php echo $this->tag->javascriptInclude( 'https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'https://cdn.jsdelivr.net/npm/jquery-throttle-debounce@1.0.0/jquery.ba-throttle-debounce.min.js', false ); ?>
<?php echo $this->tag->javascriptInclude( 'js/jquery.stickyheader.min.js?v=' . $GLOBALS['siteversion'] ); ?>
<?php echo $this->tag->javascriptInclude( 'js/base.min.js?v=' . $GLOBALS['siteversion'] ); ?>
</body>
</html>